import MSPCore

public struct MSPPOSIXCoreCommandPack: MSPCommandPack {
    public var name: String { "posix-core" }
    public let excludedCommandNames: Set<String>

    public init(excluding excludedCommandNames: Set<String> = []) {
        self.excludedCommandNames = excludedCommandNames
    }

    public func registerCommands(into registry: MSPCommandRegistry) throws {
        try register(MSPNoopCommand(), into: registry)
        try register(MSPTrueCommand(), into: registry)
        try register(MSPFalseCommand(), into: registry)
        try register(MSPTestCommand(), into: registry)
        try register(MSPTestCommand(name: "["), into: registry)
        try register(MSPTestCommand(name: "[["), into: registry)
        try register(MSPAwkCommand(), into: registry)
        try register(MSPB2SumCommand(), into: registry)
        try register(MSPBase32Command(), into: registry)
        try register(MSPBase64Command(), into: registry)
        try register(MSPBasencCommand(), into: registry)
        try register(MSPBasenameCommand(), into: registry)
        try register(MSPBcCommand(), into: registry)
        try register(MSPCdCommand(), into: registry)
        try register(MSPChmodCommand(), into: registry)
        try register(MSPCksumCommand(), into: registry)
        try register(MSPCmpCommand(), into: registry)
        try register(MSPCommCommand(), into: registry)
        try register(MSPCommandCommand(), into: registry)
        try register(MSPDateCommand(), into: registry)
        try register(MSPDiffCommand(), into: registry)
        try register(MSPDirnameCommand(), into: registry)
        try register(MSPDuCommand(), into: registry)
        try register(MSPEchoCommand(), into: registry)
        try register(MSPEnvCommand(), into: registry)
        try register(MSPFileCommand(), into: registry)
        try register(MSPCutCommand(), into: registry)
        try register(MSPDdCommand(), into: registry)
        try register(MSPGrepCommand(), into: registry)
        try register(MSPBuiltinCommand(), into: registry)
        try register(MSPPrintfCommand(), into: registry)
        try register(MSPDigestCommand(name: "md5sum", algorithm: .md5), into: registry)
        try register(MSPExpandCommand(), into: registry)
        try register(MSPExprCommand(), into: registry)
        try register(MSPFactorCommand(), into: registry)
        try register(MSPFmtCommand(), into: registry)
        try register(MSPFoldCommand(), into: registry)
        try register(MSPGroupsCommand(), into: registry)
        try register(MSPHostnameCommand(), into: registry)
        try register(MSPIdCommand(), into: registry)
        try register(MSPInstallCommand(), into: registry)
        try register(MSPJoinCommand(), into: registry)
        try register(MSPLddCommand(), into: registry)
        try register(MSPLinkCommand(), into: registry)
        try register(MSPLnCommand(), into: registry)
        try register(MSPNlCommand(), into: registry)
        try register(MSPNprocCommand(), into: registry)
        try register(MSPNumfmtCommand(), into: registry)
        try register(MSPOdCommand(), into: registry)
        try register(MSPPathchkCommand(), into: registry)
        try register(MSPPwdCommand(), into: registry)
        try register(MSPPrintenvCommand(), into: registry)
        try register(MSPPsCommand(), into: registry)
        try register(MSPReadlinkCommand(), into: registry)
        try register(MSPRealpathCommand(), into: registry)
        try register(MSPRgCommand(), into: registry)
        try register(MSPRmdirCommand(), into: registry)
        try register(MSPLsCommand(), into: registry)
        try register(MSPCatCommand(), into: registry)
        try register(MSPHeadCommand(), into: registry)
        try register(MSPCpCommand(), into: registry)
        try register(MSPMkdirCommand(), into: registry)
        try register(MSPMvCommand(), into: registry)
        try register(MSPRmCommand(), into: registry)
        try register(MSPSedCommand(), into: registry)
        try register(MSPSeqCommand(), into: registry)
        try register(MSPDigestCommand(name: "sha1sum", algorithm: .sha1), into: registry)
        try register(MSPDigestCommand(name: "sha256sum", algorithm: .sha256), into: registry)
        try register(MSPDigestCommand(name: "sha384sum", algorithm: .sha384), into: registry)
        try register(MSPDigestCommand(name: "sha512sum", algorithm: .sha512), into: registry)
        try register(MSPShufCommand(), into: registry)
        try register(MSPSleepCommand(), into: registry)
        try register(MSPSortCommand(), into: registry)
        try register(MSPSplitCommand(), into: registry)
        try register(MSPSumCommand(), into: registry)
        try register(MSPTacCommand(), into: registry)
        try register(MSPTouchCommand(), into: registry)
        try register(MSPTailCommand(), into: registry)
        try register(MSPTeeCommand(), into: registry)
        try register(MSPStatCommand(), into: registry)
        try register(MSPStringsCommand(), into: registry)
        try register(MSPTimeoutCommand(), into: registry)
        try register(MSPTrCommand(), into: registry)
        try register(MSPTreeCommand(), into: registry)
        try register(MSPTruncateCommand(), into: registry)
        try register(MSPTsortCommand(), into: registry)
        try register(MSPTtyCommand(), into: registry)
        try register(MSPTypeCommand(), into: registry)
        try register(MSPUnameCommand(), into: registry)
        try register(MSPUniqCommand(), into: registry)
        try register(MSPUnexpandCommand(), into: registry)
        try register(MSPUnlinkCommand(), into: registry)
        try register(MSPWcCommand(), into: registry)
        try register(MSPWhichCommand(), into: registry)
        try register(MSPWhoamiCommand(), into: registry)
        try register(MSPXargsCommand(), into: registry)
        try register(MSPXxdCommand(), into: registry)
        try register(MSPYesCommand(), into: registry)
        try register(MSPFindCommand(), into: registry)
        try register(MSPMktempCommand(), into: registry)
        try register(MSPPasteCommand(), into: registry)
    }

    private func register(_ command: any MSPCommand, into registry: MSPCommandRegistry) throws {
        guard !excludedCommandNames.contains(command.name) else {
            return
        }
        try registry.register(command)
    }
}
